### ISSUE TITLE
display only one day initially in DaysPageViewExample()

### ISSUE THREAD

**Issue by AnuragVadd** [ZedTheLed/calendar_views#10]
I essentially want the app to display only one day per page. I tried to mess around in the days_page_view_example.dart file but it doesnt seem to work; when i hard code the number of days to 1, the app just gets a white screen without an error. Could you please implement this option.

**Comment by The-Redhat** [comment]
Hey it would be nice if you can provide a screenshot of what you want.

**Comment by AnuragVadd** [comment]
![expected](https://user-images.githubusercontent.com/38868279/64945931-d0af2c80-d882-11e9-8132-d8fdef015438.jpg)
basically this but without the AlertDialog letting us choose how many days we want to display per page. this should be the first thing that the page should display.

**Comment by AnuragVadd** [comment]
I have implemented this by modifying the monthViewPage and converting the MonthPageView into DaysPageView
