### ISSUE TITLE
EventViewComponent not match parent

### ISSUE THREAD

**Issue by NoRamadon** [ZedTheLed/calendar_views#4]
![screen shot 2019-01-13 at 9 46 33 pm](https://user-images.githubusercontent.com/35259080/51086727-bd404480-177c-11e9-8e68-b1e22d698995.png)

How can we make it match content?

**Comment by zenled** [comment]
To change this, you must pass **DayViewWidths** to **DayViewEssentials**.
In **DayViewWidths** you can change for example *mainAreaStartPadding* and *mainAreaEndPadding* to 0.

If you want the horizontal lines (SupportLineComponent) to extend to available space (withought padding) set *totalAreaEndPadding* to 0.

```dart
new DayViewEssentials(
        properties: new DayViewProperties(
          days: <DateTime>[new DateTime.now()],
          widths: new DayViewWidths(
                           mainAreaStartPadding: 0.0,
                           mainAreaEndPadding: 0.0
                      ),
        ),
       child: ...
);
```

**Comment by NoRamadon** [comment]
@ZedTheLed  Thank you :) It work like charm
